package com.bank.BSTMS.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.bank.BSTMS.pojo.BCardInfo;

@Mapper
public interface BCardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    int insert(BCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    int insertSelective(BCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    BCardInfo selectByPrimaryKey(String cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BCardInfo record);
}