package com.bank.BSTMS.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account
 */
public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.cardid
     *
     * @mbg.generated
     */
    private String cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.accountBalance
     *
     * @mbg.generated
     */
    private Double accountbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.identify
     *
     * @mbg.generated
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.authority
     *
     * @mbg.generated
     */
    private String authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.creditlimit
     *
     * @mbg.generated
     */
    private String creditlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.effectiveDate
     *
     * @mbg.generated
     */
    private String effectivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.isdel
     *
     * @mbg.generated
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.cardid
     *
     * @return the value of account.cardid
     *
     * @mbg.generated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.cardid
     *
     * @param cardid the value for account.cardid
     *
     * @mbg.generated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.accountBalance
     *
     * @return the value of account.accountBalance
     *
     * @mbg.generated
     */
    public Double getAccountbalance() {
        return accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.accountBalance
     *
     * @param accountbalance the value for account.accountBalance
     *
     * @mbg.generated
     */
    public void setAccountbalance(Double accountbalance) {
        this.accountbalance = accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.identify
     *
     * @return the value of account.identify
     *
     * @mbg.generated
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.identify
     *
     * @param identify the value for account.identify
     *
     * @mbg.generated
     */
    public void setIdentify(String identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.type
     *
     * @return the value of account.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.type
     *
     * @param type the value for account.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.authority
     *
     * @return the value of account.authority
     *
     * @mbg.generated
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.authority
     *
     * @param authority the value for account.authority
     *
     * @mbg.generated
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.creditlimit
     *
     * @return the value of account.creditlimit
     *
     * @mbg.generated
     */
    public String getCreditlimit() {
        return creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.creditlimit
     *
     * @param creditlimit the value for account.creditlimit
     *
     * @mbg.generated
     */
    public void setCreditlimit(String creditlimit) {
        this.creditlimit = creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.effectiveDate
     *
     * @return the value of account.effectiveDate
     *
     * @mbg.generated
     */
    public String getEffectivedate() {
        return effectivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.effectiveDate
     *
     * @param effectivedate the value for account.effectiveDate
     *
     * @mbg.generated
     */
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.isdel
     *
     * @return the value of account.isdel
     *
     * @mbg.generated
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.isdel
     *
     * @param isdel the value for account.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}